# home
root:
    path: /
    defaults:
        resource: "landing"
    methods: [GET, POST]
    
tags:
    path: /{resource}{slash}
    requirements:
        resource: "tags"
        slash: "[/]{0,1}"
    methods: [GET,POST,DELETE,PUT]

actionincluded:
    path: /{resource}{slash}{action}
    requirements:
        resource: "tags"
        slash: "[/]{0,1}"
    methods: [GET,POST,DELETE,PUT]
